"""changed heading

Revision ID: 17bb35a45b27
Revises: 305aaee7cc81
Create Date: 2024-08-02 00:28:25.877902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17bb35a45b27'
down_revision = '305aaee7cc81'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('portfoliorecords', schema=None) as batch_op:
        batch_op.drop_constraint('fk_destination_pid', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfoliorecords', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_destination_pid', 'portfolio', ['destination_pid'], ['pid'], ondelete='SET NULL')
