"""Add SharedSL model

Revision ID: 85e2c156496c
Revises: eec368cd1c75
Create Date: 2024-08-02 04:02:28.388027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e2c156496c'
down_revision = 'eec368cd1c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sharedsl',
    sa.Column('slid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['slid'], ['stocklist.slid'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('slid', 'username')
    )

    # ### end Alembic commands ###


def downgrade():

    op.drop_table('sharedsl')
    # ### end Alembic commands ###
