"""Initial migration.

Revision ID: c98469ca6e86
Revises: 
Create Date: 2024-07-31 17:52:04.956260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98469ca6e86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testtbl')
    with op.batch_alter_table('cashaccount', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'users', ['username'], ['username'])

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.alter_column('pname',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('userid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'users', ['userid'], ['username'])

    with op.batch_alter_table('portfolioholding', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('volume',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('slconsists', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('volume',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('slowners', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'users', ['username'], ['username'])

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)

    with op.batch_alter_table('stockhistory', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('high',
               existing_type=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('low',
               existing_type=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('open',
               existing_type=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('close',
               existing_type=sa.NUMERIC(),
               nullable=True)
        batch_op.create_foreign_key(None, 'stock', ['symbol'], ['symbol'])

    with op.batch_alter_table('stocklist', schema=None) as batch_op:
        batch_op.alter_column('slname',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('publicity',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=64),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('stocklist', schema=None) as batch_op:
        batch_op.alter_column('publicity',
               existing_type=sa.String(length=64),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
        batch_op.alter_column('slname',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('stockhistory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('close',
               existing_type=sa.NUMERIC(),
               nullable=False)
        batch_op.alter_column('open',
               existing_type=sa.NUMERIC(),
               nullable=False)
        batch_op.alter_column('low',
               existing_type=sa.NUMERIC(),
               nullable=False)
        batch_op.alter_column('high',
               existing_type=sa.NUMERIC(),
               nullable=False)
        batch_op.alter_column('symbol',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('symbol',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('slowners', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('slconsists', schema=None) as batch_op:
        batch_op.alter_column('volume',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('symbol',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('portfolioholding', schema=None) as batch_op:
        batch_op.alter_column('volume',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('symbol',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('userid',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('pname',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('cashaccount', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)

    op.create_table('testtbl',
    sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
