"""Add destination_pid to PortfolioRecords

Revision ID: d4b2edb9e3ca
Revises: efa75f9d57d2
Create Date: 2024-08-02 00:16:30.929801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b2edb9e3ca'
down_revision = 'efa75f9d57d2'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('portfoliorecords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_pid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'portfolio', ['destination_pid'], ['pid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfoliorecords', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('destination_pid')

    # ### end Alembic commands ###
