"""Add Friends table

Revision ID: f02a041a937f
Revises: 196f714b3c38
Create Date: 2024-08-01 16:41:25.634362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02a041a937f'
down_revision = '196f714b3c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('user_id1', sa.String(length=64), nullable=False),
    sa.Column('user_id2', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id1'], ['users.username'], ),
    sa.ForeignKeyConstraint(['user_id2'], ['users.username'], ),
    sa.PrimaryKeyConstraint('user_id1', 'user_id2'),
    sa.UniqueConstraint('user_id1', 'user_id2', name='unique_friendship')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###
